### ISSUE TITLE
[新特性] 添加创作者名单以及特别鸣谢

### ISSUE THREAD

**Issue by Seayay** [Heart-Fire-Project/midnight-soul#20]
这一块应该放在大厅里，所以得先做完 #19

**Comment by Roser7419** [comment]
思遥方会用 text_display 吗

**Comment by Seayay** [comment]
不会



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年09月16日 00:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Heart-Fire-Project/midnight-soul-dp] [新特性] 添加创作者名单以及特别鸣谢 (Issue #20) |

思遥方会用 text_display 吗

**Comment by Roser7419** [comment]
再等等，等测试结束的
