### ISSUE TITLE
[新功能] 大厅新增功能总览

### ISSUE THREAD

**Issue by Roser7419** [Heart-Fire-Project/midnight-soul#24]
#19 主要针对于把新大厅建出来，这里写的都是技术组的事情、
按照我本人的设计，在新大厅中会有一块区域可以随选择转变为各种项目的设置
比如在地图选择时可以展示地图的对应微缩模型，也可以转变为选择职业的地方
### 地图选择
你真觉得玩家能根据我写的那些倒霉玩意知道地图都是啥?
### 自选职业
你知道的，墨鱼哥上次测试连着杀了三把

**Comment by Seayay** [comment]
建筑组的大爹在做了

**Comment by Seayay** [comment]
- [ ] 游戏设置
- [ ] 大厅跑酷（也可以不做）
- [ ] 微缩地图（但我不会做）

@Roser7419

**Comment by XieXiLin2** [comment]
🕊️
