### ISSUE TITLE
[游戏优化] 更改终局机制触发条件

### ISSUE THREAD

**Issue by Seayay** [Heart-Fire-Project/midnight-soul#34]
### 建议内容

将 **剩余一人** 触发调整为 **剩余一人并再收集 4 个灵魂碎片** 触发
若场上无足够数量的灵魂碎片：清除所有灵魂碎片，并随机刷新 8 个灵魂碎片

### 优化内容

防止玩家消极游戏

**Comment by Roser7419** [comment]
取消，但是仍然不会立即开启，而是直接转到 20 分钟的终局机制
